[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
log = "0.4.21"
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
serde = { version = "1.0.203", features = ["serde_derive", "derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
